dao.usuario=com.ipartek.formacion.ejemplos.ipartex.accesodatos.jpa.DaoUsuarioJpa
dao.mensaje=com.ipartek.formacion.ejemplos.ipartex.accesodatos.jpa.DaoMensajeJpa

negocio.anonimo=com.ipartek.formacion.ejemplos.ipartex.logicanegocio.impl.AnonimoNegocioImpl
negocio.usuario=com.ipartek.formacion.ejemplos.ipartex.logicanegocio.impl.UsuarioNegocioImpl
