spring.application.name=amazonia

spring.datasource.url=jdbc:sqlite:amazonia.db
spring.datasource.username=
spring.datasource.password=

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.data.rest.base-path=/api/v1

spring.devtools.livereload.enabled=true

springdoc.enable-data-rest=false
springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/api/ui

spring.web.locale=es_ES
spring.web.locale-resolver=fixed
