dao.jdbc=bibliotecas.accesodatos.DaoJdbcImpl

dao.persona=com.ipartek.formacion.ejemplos.ejemploweb.accesodatos.DaoPersonaSqliteGenerico
dao.rol=com.ipartek.formacion.ejemplos.ejemploweb.accesodatos.DaoRolSqliteGenerico

fecha=java.util.GregorianCalendar
